/* File: PlumeGen.c
 * Athr: Dimitri Zarzhitsky
 * Date: November 1, 2004
 *
 * Desc: Plume generator for Fluxotaxis testing.  This file only includes plume
 *       generation, lattice traces are generated by "TraceGen.c".  Current
 *       forward solution is achieved via Farrell's plume simulator. 
 *
 * Note: August 9, 2008 - Dimitri refactored velocity functions to incorporate the 
 *                        latest fixes in the obstacle-handling code.
 */
#include "Common.h"
#include <sys/stat.h>
#include "Scenario.h"

#define PATH_DENSITY_FILES  "Webots/density"
#define DENSITY_FILE_NAME   "density.txt"

#define PATH_VELOCITY_FILES  "Webots/velocity"
#define VELOCITY_X_FILE_NAME "velocityX.txt"
#define VELOCITY_Y_FILE_NAME "velocityY.txt"

map_t MAP;
flt_t *U, *V, *RHO, *SCRATCH;

// dimzar-20080809: added persistent file pointers to improve IO performance
FILE* TXT_FILE_RHO;
FILE* TXT_FILE_U;
FILE* TXT_FILE_V;

typedef struct fillament {
  flt_t x;
  flt_t y;
  flt_t r;
  flt_t t;
} puff_t;
puff_t *PUFFS;
int     NUM_PUFFS;

// COPY from Farrell's Integral.cpp
flt_t X_BOUNDARY[8] = {0,0,0,0,0,0,0,0}, Y_BOUNDARY[8] = {0,0,0,0,0,0,0,0};


// ##### MEMORY UTILS #####
void alloc_mem() {
  U       = calloc(MAP.nxy, sizeof(flt_t));
  V       = calloc(MAP.nxy, sizeof(flt_t));
  RHO     = calloc(MAP.nxy, sizeof(flt_t));
  SCRATCH = calloc(MAP.nxy, sizeof(flt_t));

  PUFFS     = calloc(MAX_PUFFS, sizeof(puff_t));
  NUM_PUFFS = 0;
}

void free_mem() {
  free(PUFFS);

  free(SCRATCH);
  free(RHO);
  free(V);
  free(U);

  free(MAP.world);
}


// ##### FILE IO #####
void error_exit(const char *template, ...) __attribute__ ((noreturn, format(printf, 1, 2)));
void error_exit(const char *template, ...) {
  free_mem();
  va_list ap;
  va_start(ap, template);
  vfprintf(stderr, template, ap);
  va_end(ap);
  fprintf(stderr, "\n");
  abort();
}

void write_header(FILE *out) {
  const char format_id[] = FILE_VER_PLUME;
  fwrite(format_id, sizeof(char), FILE_VER_LENGTH_PLUME, out);

  fwrite(&MAP,      sizeof(int),  3,       out);
  fwrite(MAP.world, sizeof(char), MAP.nxy, out);
  
  int params[] = {CPT_STEPS/VIS_REDUCTION, SOURCE_EX, SOURCE_EY};
  fwrite(params, sizeof(int), 3, out);
}

void init_frame_file(const char* filename, FILE** file)
{
    *file = fopen(filename, "w");
    if (!*file) error_exit(" (!) cannot open '%s' for writing frame data file\n", filename);
}

void init_frame_files()
{
  TXT_FILE_RHO = NULL;
  TXT_FILE_U   = NULL;
  TXT_FILE_V   = NULL;

#ifdef PATH_DENSITY_FILES
  if (g_mkdir_with_parents(PATH_DENSITY_FILES, S_IRUSR|S_IWUSR|S_IXUSR|S_IRGRP|S_IXGRP|S_IROTH|S_IXOTH)) { 
      perror("PlumeGen::init_frame_files()"); 
      error_exit(" (!) cannot create output directory for storing density data TXT files"); 
  }

  char rho_filename[PATH_MAX+1];
  rho_filename[PATH_MAX] = '\0';
  snprintf(rho_filename, PATH_MAX, PATH_DENSITY_FILES"/"DENSITY_FILE_NAME);
  init_frame_file(rho_filename, &TXT_FILE_RHO);
#endif //PATH_DENSITY_FILES

#ifdef PATH_VELOCITY_FILES
  if (g_mkdir_with_parents(PATH_VELOCITY_FILES, S_IRUSR|S_IWUSR|S_IXUSR|S_IRGRP|S_IXGRP|S_IROTH|S_IXOTH)) { 
      perror("PlumeGen::init_frame_files()"); 
      error_exit(" (!) cannot create output directory for storing velocity data TXT files"); 
  }
  char vel_filename[PATH_MAX+1];
  vel_filename[PATH_MAX] = '\0';
  snprintf(vel_filename, PATH_MAX, PATH_VELOCITY_FILES"/"VELOCITY_X_FILE_NAME);
  init_frame_file(vel_filename, &TXT_FILE_U);

  snprintf(vel_filename, PATH_MAX, PATH_VELOCITY_FILES"/"VELOCITY_Y_FILE_NAME);
  init_frame_file(vel_filename, &TXT_FILE_V);
#endif //PATH_VELOCITY_FILES
}

void finalize_frame_files()
{
    if (TXT_FILE_RHO && fclose(TXT_FILE_RHO)) perror(" (!) PlumeGen::finalize_frame_file() cannot close density data TXT file");
    if (TXT_FILE_U && fclose(TXT_FILE_U))     perror(" (!) PlumeGen::finalize_frame_file() cannot close X-component of velocity data TXT file");
    if (TXT_FILE_V && fclose(TXT_FILE_V))     perror(" (!) PlumeGen::finalize_frame_file() cannot close Y-component of velocity data TXT file");
}

int write_frame(FILE* file, flt_t data[MAP.nxy]) {
  // WMS - changed "," delimited to space delimited
  for (int i=0; i<MAP.nxy-1; i++) fprintf(file, "%f ", data[i]);
  fprintf(file, "%f\n", data[MAP.nxy-1]);

  return ferror(file);
}

void write_step(int step, FILE *out) {
  fwrite(&step, sizeof(int),   1,       out);
  fwrite(U,     sizeof(flt_t), MAP.nxy, out);
  fwrite(V,     sizeof(flt_t), MAP.nxy, out);
  fwrite(RHO,   sizeof(flt_t), MAP.nxy, out);

  if (ferror(out)) {
      perror(" (!) PlumeGen::write_step()");
      error_exit(" (!) cannot save plume data");
  }

#ifdef PATH_DENSITY_FILES
  if (write_frame(TXT_FILE_RHO, RHO)) error_exit(" (!) PlumeGen::write_step() cannot save density data into the '"DENSITY_FILE_NAME"' file\n");
#endif //PATH_DENSITY_FILES

#ifdef PATH_VELOCITY_FILES
  if (write_frame(TXT_FILE_U, U)) error_exit(" (!) PlumeGen::write_step() cannot save X-component of velocity data into the '"VELOCITY_X_FILE_NAME"' file\n");
  if (write_frame(TXT_FILE_V, V)) error_exit(" (!) PlumeGen::write_step() cannot save Y-component of velocity data into the '"VELOCITY_Y_FILE_NAME"' file\n");
#endif //PATH_VELOCITY_FILES
}


// ##### MAP UTILS #####
#define MAX_WORLD_WIDTH 1024
#define LINE_BUFFER_SIZE (MAX_WORLD_WIDTH + 3)
//WMS
//#define MIN_EMITTER_CLEARANCE 5
#define MIN_EMITTER_CLEARANCE 2

void read_map_file(const char *filename) {
  FILE *map_file = fopen(filename, "r");
  if (!map_file) error_exit(" (!) cannot open map file '%s'", filename);
  
  char line[LINE_BUFFER_SIZE];
  if (!fgets(line, LINE_BUFFER_SIZE, map_file)) error_exit(" (!) empty map file '%s' (maybe an IO error)", filename);
  size_t end_of_line = strlen(line);
  if (end_of_line-1 > MAX_WORLD_WIDTH) error_exit(" (!) map in '%s' is too large (current max size = %d)", filename, MAX_WORLD_WIDTH);
  if (end_of_line<2 || line[end_of_line-1]!='\n') error_exit(" (!) first line of map file '%s' is corrupted", filename);
  MAP.ny = (long)(end_of_line-1);
  MAP.nx = 1;
  line[MAP.ny] = '\0';
  while (fgets(line, LINE_BUFFER_SIZE, map_file)) {
    MAP.nx++;
    if (line[MAP.ny]!='\n') error_exit(" (!) map file '%s' is corrupted on line %d", filename, MAP.nx);
    line[MAP.ny] = '\0';
  }
  if (MAP.ny != MAP.nx) error_exit(" (!) map in '%s' is not a square (%d x %d) --unsupported feature--", filename, MAP.ny, MAP.nx);
  MAP.nxy = MAP.nx * MAP.ny;
  MAP.world = calloc(MAP.nxy, sizeof(char));
  rewind(map_file);
  for (int i=0; i<MAP.nx; i++) fgets(MAP.world+i*MAP.ny, end_of_line, map_file), fgetc(map_file);

  if (!map_is_world_region_square(SOURCE_EX, SOURCE_EY, MIN_EMITTER_CLEARANCE)) {
    error_exit(" (!) emitter at (%d,%d) is less than %d units away from the world boundary", SOURCE_EX, SOURCE_EY, MIN_EMITTER_CLEARANCE);
  }
  if (map_is_blocked_region_square(SOURCE_EX, SOURCE_EY, MIN_EMITTER_CLEARANCE)) {
    error_exit(" (!) emitter at (%d,%d) is less than %d units away from an obstacle", SOURCE_EX, SOURCE_EY, MIN_EMITTER_CLEARANCE);
  }
}


// ##### VELOCITY #####
// COPY from Farrell's Integral.cpp ->
// produces a unit variance normal random variable
flt_t nrand() {
  // a more efficient implementation per http://en.wikipedia.org/wiki/Normal_distribution
  flt_t a = random()/(flt_t)RAND_MAX, b = random()/(flt_t)RAND_MAX;
  return sqrt(-2 * log(a)) * cos(2*M_PI*b);

  /*
  flt_t r=0;
  const int NN = 10;
  for(int i=0; i<NN; i++) r+=((flt_t)random()/RAND_MAX);
  r = (r-(flt_t)NN/2)*2*sqrt(3/(flt_t)NN);
  return r;
  */
}

// COPY from Farrell's Integral.cpp ->
/*
 * produces a colored noise process. With coloring process
 *                      G wind_bandwidth*wind_bandwidth
 *            H(s)=--------------------
 *                  s*s+2*z*wind_bandwidth*s+wind_bandwidth*wind_bandwidth
 *   G = wind_gain is the DC gain (variance)
 *   wind_bandwidth is the natural frequency (bandwidth)
 *   z = wind_damping is the damping coefficient
 *   all three parameters are predfined.
 */
flt_t colored_noise(flt_t *x, flt_t dt) {
  //const flt_t wind_damping = .2, wind_bandwidth = .25132744, wind_gain = 5;
  //const flt_t wind_damping = .05, wind_bandwidth = .01, wind_gain = 0.73;
  flt_t dx[2];
  flt_t u = nrand();
  dx[0] = x[1];
  dx[1] = -2*WIND_DAMPING*WIND_BANDWIDTH*x[1] + WIND_BANDWIDTH*WIND_BANDWIDTH*(-x[0] + WIND_GAIN*u);
  x[0] += dx[0]*dt;
  x[1] += dx[1]*dt;
  return(x[0]);
}

void compute_bc(flt_t c1, flt_t c2, const flt_t speedc[4], const flt_t *u, const flt_t *v, flt_t *mesh) {

  // WMS I think the corner computations are ok - no ordering problems
  mesh[0] = (c1*(mesh[MAP.ny] + speedc[0] + mesh[1] + speedc[0] - 4*mesh[0]) -
	     c2*u[0]*(mesh[MAP.ny] - speedc[0]) - c2*v[0]*(mesh[1] - speedc[0]));
  mesh[MAP.ny-1] = (c1*(mesh[2*MAP.ny-1] + speedc[1] + speedc[1] + mesh[MAP.ny-2] - 4*mesh[MAP.ny-1]) -
		    c2*u[MAP.ny-1]*(mesh[2*MAP.ny-1] - speedc[1]) - c2*v[MAP.ny-1]*(speedc[1] - mesh[MAP.ny-2]));
  mesh[MAP.nxy-MAP.ny] = (c1*(speedc[2] + mesh[MAP.nxy-2*MAP.ny] + mesh[MAP.nxy-MAP.ny+1] + speedc[2] - 4*mesh[MAP.nxy-MAP.ny]) -
			  c2*u[MAP.nxy-MAP.ny]*(speedc[2] - mesh[MAP.nxy-2*MAP.ny]) - c2*v[MAP.nxy-MAP.ny]*(mesh[MAP.nxy-MAP.ny+1] - speedc[2]));
  mesh[MAP.nxy-1] = (c1*(speedc[3] + mesh[MAP.nxy-MAP.ny-1] + speedc[3] + mesh[MAP.nxy-2] - 4*mesh[MAP.nxy-1]) -
		     c2*u[MAP.nxy-1]*(speedc[3] - mesh[MAP.nxy-MAP.ny-1]) - c2*v[MAP.nxy-1]*(speedc[3] - mesh[MAP.nxy-2]));
  

  // WMS I think the edge computations are ok - no ordering problems
  // linear interpolation of "edge nodes"
  const flt_t del_top = (mesh[MAP.ny-1] - mesh[0])/(MAP.ny-1);
  for (int j=1; j<MAP.ny-1; j++) mesh[j] = mesh[0] + del_top*j;
  
  const flt_t del_bot = (mesh[MAP.nxy-1] - mesh[MAP.nxy-MAP.ny])/(MAP.ny-1);
  for (int j=1; j<MAP.ny-1; j++) mesh[MAP.nxy-MAP.ny+j] = mesh[MAP.nxy-MAP.ny] + del_bot*j;
  
  const flt_t del_left = (mesh[MAP.nxy-MAP.ny] - mesh[0])/(MAP.nx-1);
  for (int i=1; i<MAP.nx-1; i++) mesh[i*MAP.ny] = mesh[0] + del_left*i;
  
  const flt_t del_right = (mesh[MAP.nxy-1] - mesh[MAP.ny-1])/(MAP.nx-1);
  for (int i=1; i<MAP.nx-1; i++) mesh[i*MAP.ny+MAP.ny-1] = mesh[MAP.ny-1] + del_right*i;
}

// OBSTACLE - VERSION 3 by WMS with minor mods by dimzar
void compute_obstacle_bc(flt_t *wind_vector_component) {
  memcpy(SCRATCH, wind_vector_component, MAP.nxy*sizeof(flt_t));
  for (int i=1; i<MAP.nx-1; i++) {
    for (int j=1; j<MAP.ny-1; j++) {
      if (map_is_blocked_region_square(i, j, 1)) {
        const int index = i*MAP.ny + j;
        // WMS Edits to "non-slip condition" stuff here
        // I want the wind to not damp down as fast. The original
        // value to divide by was 5. It should be >= 4.
        SCRATCH[index] = (wind_vector_component[index-1] + 
			  wind_vector_component[index+1] + 
			  wind_vector_component[index-MAP.ny] + 
			  wind_vector_component[index+MAP.ny]) / 4.1;
      }
    }
  }
  memcpy(wind_vector_component, SCRATCH, MAP.nxy*sizeof(flt_t));
}

void compute_mesh_CD(flt_t c1, flt_t c2, const flt_t *u, const flt_t *v, flt_t *mesh) {
  memcpy(SCRATCH, mesh, MAP.nxy*sizeof(flt_t));
  for (int i=1; i<MAP.nx-1; i++) {
    for (int j=1; j<MAP.ny-1; j++) {
      const int index = i*MAP.ny+j;
      SCRATCH[index] += (c1*(mesh[index+MAP.ny] + mesh[index-MAP.ny] + mesh[index+1] + mesh[index-1] - 4*mesh[index]) -
			 c2*u[index]*(mesh[index+MAP.ny] - mesh[index-MAP.ny]) - c2*v[index]*(mesh[index+1] - mesh[index-1]));

      if (!finite(SCRATCH[index])) error_exit(" (!) solution blew up");
    }
  }
  memcpy(mesh, SCRATCH, MAP.nxy*sizeof(flt_t));
}

void compute_velocity(flt_t *u, flt_t *v) {
  //void compute_velocity(flt_t *u, flt_t *v) {
  const flt_t c1 = K*DEL_T/2, c2 = DEL_T/2;
  
  // COPY from Farrell's Integral.cpp ->
  // Generate colored noise boundary conditions stochastic
  flt_t speedxc[4], speedyc[4];
  for(int i=0; i<4; i++){                        
    speedxc[i] = MEAN_U + colored_noise(X_BOUNDARY+2*i, 1);
    speedyc[i] = MEAN_V + colored_noise(Y_BOUNDARY+2*i, 1); 
  }

  // WMS Really have to wonder if order matters here...
  compute_bc(c1, c2, speedxc, u, v, u);
  compute_bc(c1, c2, speedyc, u, v, v);

  // WMS Really have to wonder if order matters here...
  compute_mesh_CD(c1, c2, u, v, u);
  compute_mesh_CD(c1, c2, u, v, v);
 
  compute_obstacle_bc(u);
  compute_obstacle_bc(v);
}


// ##### DENSITY #####
/* uniform [0,1] random number generator developed by Pierre Lecuyer based on a clever
   and tested combination of two linear congruential sequences: http://cgm.cs.mcgill.ca/~luc/rng.html
*/
flt_t lecuyer_uni_rand() {
  // s1 and s2 are the seeds (nonnegative integers)
  static long s1 = 55555, s2 = 99999;
  static flt_t factor = 1.0/2147483563.0;
  register long k,z;

  k  = s1 / 53668;
  s1 = 40014 * (s1%53668) - k*12211;
  if (s1 < 0) s1 += 2147483563;

  k  = s2 / 52774;
  s2 = 40692 * (s2%52774) - k*3791;
  if (s2 < 0) s2 += 2147483399;
  /*
    z = abs(s1 ^ s2);
  */
  z = (s1 - 2147483563) + s2;
  if (z < 1) z += 2147483562;
  return z*factor;
}

void add_puffs(puff_t *puffs) {
  for (int i=NUM_PUFFS; i<NUM_PUFFS+EMIT_RATE; i++) {
    puffs[i].x = SOURCE_EX + (1 - 2*lecuyer_uni_rand());
    puffs[i].y = SOURCE_EY + (1 - 2*lecuyer_uni_rand());
    puffs[i].r = R0;
    puffs[i].t = 0;
  }
  NUM_PUFFS += EMIT_RATE;
  assert(NUM_PUFFS < MAX_PUFFS);
}

void remove_puffs(puff_t *puffs) {
  for (int p=0; p<NUM_PUFFS; p++) {
    const flt_t x = puffs[p].x, y = puffs[p].y, r = puffs[p].r;
    if (x >= MAP.nx+r || x < -r || y >= MAP.ny+r || y < -r) puffs[p--] = puffs[--NUM_PUFFS];
  }
}

void move_puffs(const flt_t *u, const flt_t *v, puff_t *puffs) {
  add_puffs(puffs);
  for (int p=0; p<NUM_PUFFS; p++) {
    const int x = lround(puffs[p].x), y = lround(puffs[p].y);
    if (map_is_world_point(x, y)) {
      const int index = x*MAP.ny + y;
      flt_t new_x = puffs[p].x + u[index]*(1 + SIGMA_NUX*(1 - 2.*lecuyer_uni_rand())) * DEL_T;
      flt_t new_y = puffs[p].y + v[index]*(1 + SIGMA_NUY*(1 - 2.*lecuyer_uni_rand())) * DEL_T;

      if (map_is_blocked_point(new_x, new_y)) {
	if (!map_is_blocked_point(new_x, puffs[p].y)) puffs[p].x = new_x;
	else if (!map_is_blocked_point(puffs[p].x, new_y)) puffs[p].y = new_y;
	else {
	  // try a new position by reflecting the puff
	  flt_t theta = atan2(puffs[p].y-new_y, puffs[p].x-new_x), r = hypot(puffs[p].x-new_x, puffs[p].y-new_y);
	  flt_t theta_offset = M_PI/4;
	  flt_t x_plus  = new_x + r*cos(theta+theta_offset), y_plus  = new_y + r*sin(theta+theta_offset);
	  flt_t x_minus = new_x + r*cos(theta-theta_offset), y_minus = new_y + r*sin(theta-theta_offset);
	  if (!map_is_blocked_point(x_plus, y_plus)) puffs[p].x = x_plus, puffs[p].y = y_plus;
	  else if (!map_is_blocked_point(x_minus, y_minus)) puffs[p].x = x_minus, puffs[p].y = y_minus;
	  // otherwise, give up and just keep the puff where it was prior to this step
	}
      } else {
	puffs[p].x = new_x;
	puffs[p].y = new_y;
      }
      assert(!map_is_blocked_point(puffs[p].x, puffs[p].y));
    } else {
      // puffs are outside the world, where they move with the average velocity
      puffs[p].x += MEAN_U * DEL_T;
      puffs[p].y += MEAN_V * DEL_T;
    }
    puffs[p].r  = sqrt(R0*R0 + GAMMA*puffs[p].t);
    puffs[p].t += DEL_T; 
  }
  remove_puffs(puffs);
}

//#define COEFFICIENT (Q/sqrt(8*pow(M_PI, 3)))
#define COEFFICIENT (Q/15.7496)
void compute_puff_rho_impact(flt_t dist, flt_t puff_r, flt_t *rho_cell) {
  if (dist <= puff_r) *rho_cell += COEFFICIENT/(puff_r*puff_r*puff_r) * exp(-dist*dist/(puff_r*puff_r));
}

// If one of the puff points falls inside an obstacle, treat it as though
// it belongs to an unoccupied cell right before the obstacle and lies on
// the line between the intended point and the center of the puff.
void compute_density(const puff_t *puffs, flt_t *rho) {
  memset(rho, 0, MAP.nxy*sizeof(flt_t));
  for (int p=0; p<NUM_PUFFS; p++) {
    const puff_t *puff = puffs+p;
    const flt_t x = puff->x, y = puff->y, r = puff->r;
    int beg_i = fmin(MAP.nx-1, fmax(0, x-r)), beg_j = fmin(MAP.ny-1, fmax(0, y-r));
    int end_i = fmin(MAP.nx-1, fmax(0, x+r)), end_j = fmin(MAP.ny-1, fmax(0, y+r));
    for (int i=beg_i; i<=end_i; i++) {
      for (int j=beg_j; j<=end_j; j++) {
	if (map_is_blocked_point(i, j)) {
	  flt_t hit_x = i, hit_y = j;
	  if (fabs(x-i) > 1) {
	    // Use two-point equation: y = mx - mX1 + Y1, where X1 and Y1 are coordiantes of the puff center
	    const flt_t slope = (y-j)/(x-i), point_slope_offset = -slope*x + y, step = (i<x ? .5 : -.5);
	    while (map_is_blocked_point(hit_x+=step, hit_y=slope*hit_x+point_slope_offset));
	  } else {
	    const flt_t step = (j<y ? .5 : -.5);
	    while(map_is_blocked_point(hit_x, hit_y+=step)); 
	  }
	  if (map_is_world_point(hit_x, hit_y)) compute_puff_rho_impact(hypot(x-hit_x, y-hit_y), r, rho + (int)hit_x*MAP.ny+(int)hit_y);
	  else {fprintf(stderr, "i=%d, j=%d, x=%f, y=%f, hit_x=%f, hit_y=%f\n", i, j, x, y, hit_x, hit_y); /*assert(FALSE);*/}
	} else {
	  compute_puff_rho_impact(hypot(x-i, y-j), r, rho + i*MAP.ny+j);
	}
      }
    }
  }
}

//##########
int main(int argc, char *argv[]) {
  if (argc < 2) fprintf(stderr, "Usage: pgen map_file\n"), abort();

  srandom(2); // WMS - set the seed!

  char map_file[PATH_MAX+1];
  PARSE_FILENAME_FROM_PATH(argv[1], "map", map_file);
  char plume_path_file[PATH_MAX+1];
  plume_path_file[PATH_MAX] = '\0';
  snprintf(plume_path_file, PATH_MAX, "%s_%s", DEFAULT_FILENAME_PLUME, map_file);
  fprintf(stdout, "\nGenerating plume data file '%s' ...\n", plume_path_file), fflush(stdout);

  read_map_file(argv[1]);
  fprintf(stdout, " (*) map obstacle coverage: %.1f%%\n", map_percent_blocked()), fflush(stdout);

  FILE *out = fopen(plume_path_file, "w");
  if (!out) error_exit(" (!) cannot open '%s' for writing", plume_path_file);

  // dimzar-20080809: create TXT data files if requested
  init_frame_files();

  write_header(out);
  alloc_mem();

  for (int i=0; i<MAP.nxy; i++) {
    U[i] = MEAN_U;
    V[i] = MEAN_V;
  }

  for (int prep=0; prep<PREP_STEPS; prep++) {
    compute_velocity(U, V);
    move_puffs(U, V, PUFFS);
  }
  compute_density(PUFFS, RHO);
  write_step(0, out);
  for (int t=1; t<CPT_STEPS && !ferror(out); t++) {
    if (!(t%VIS_REDUCTION)) fprintf(stdout, "%3.0f%%\b\b\b\b", 100.*t/CPT_STEPS), fflush(stdout);
    
    compute_velocity(U, V);
    move_puffs(U, V, PUFFS);
    
    if (!(t%VIS_REDUCTION)) compute_density(PUFFS, RHO), write_step(t/VIS_REDUCTION, out);
  }
  if (ferror(out)) error_exit(" (!) output stream %p:'%s' failed", (void*)out, plume_path_file);

  fclose(out);
  finalize_frame_files();

  free_mem();
  fprintf(stdout, "complete.\n\n");
  return 0;
}
